import { MotionTemplate, MotionParams } from '../types';

export function generateStandaloneJsCode(
  template: MotionTemplate,
  params: MotionParams,
  duration: number
): string {
  return `/**
 * Pure HTML5 Canvas API Motion Graphic Generator
 * Template: ${template.name}
 * Duration: ${duration}s (Seamless Loop)
 * Generated by Microstock Motion Graphics Studio
 */

(function () {
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  document.body.appendChild(canvas);

  canvas.style.position = 'fixed';
  canvas.style.top = '0';
  canvas.style.left = '0';
  canvas.style.width = '100vw';
  canvas.style.height = '100vh';
  canvas.style.zIndex = '-1';

  let width, height;
  function resize() {
    width = canvas.width = window.innerWidth * window.devicePixelRatio;
    height = canvas.height = window.innerHeight * window.devicePixelRatio;
  }
  window.addEventListener('resize', resize);
  resize();

  const DURATION = ${duration}; // seconds
  const PARAMS = ${JSON.stringify(params, null, 2)};

  function getLoopProgress(time, duration) {
    const t = time % duration;
    return t < 0 ? (t + duration) / duration : t / duration;
  }

  function sinLoop(progress, multiplier = 1, phase = 0) {
    return Math.sin(progress * Math.PI * 2 * multiplier + phase);
  }

  function cosLoop(progress, multiplier = 1, phase = 0) {
    return Math.cos(progress * Math.PI * 2 * multiplier + phase);
  }

  let startTime = null;

  function render(timestamp) {
    if (!startTime) startTime = timestamp;
    const time = (timestamp - startTime) / 1000;

    // Render Canvas Logic
    ctx.clearRect(0, 0, width, height);
    
    // Background
    ctx.fillStyle = PARAMS.bgColor;
    ctx.fillRect(0, 0, width, height);

    ctx.save();
    ctx.globalCompositeOperation = PARAMS.blendMode;

    // Primary Animated Loop
    const progress = getLoopProgress(time, DURATION);
    const cx = width / 2;
    const cy = height / 2;

    // Drawing particle wave / HUD graphics
    ctx.fillStyle = PARAMS.primaryColor;
    ctx.strokeStyle = PARAMS.secondaryColor;
    ctx.lineWidth = PARAMS.lineThickness * window.devicePixelRatio;

    const count = PARAMS.particleCount;
    for (let i = 0; i < count; i++) {
      const pAngle = (i / count) * Math.PI * 2 + progress * Math.PI * 2 * PARAMS.speed;
      const radius = (Math.min(width, height) * 0.3) + sinLoop(progress + i * 0.1, 1) * 20;
      const x = cx + Math.cos(pAngle) * radius;
      const y = cy + Math.sin(pAngle) * radius;

      ctx.beginPath();
      ctx.arc(x, y, 3 * window.devicePixelRatio, 0, Math.PI * 2);
      ctx.fill();
    }

    ctx.restore();

    requestAnimationFrame(render);
  }

  requestAnimationFrame(render);
})();
`;
}
